services:
  - type: web
    name: student-portfolio
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        value: change-this-secret
      - key: APP_FRONTEND_ORIGIN
        value: https://student-portfolio.onrender.com
      - key: DB_URL
        value: jdbc:mysql://<MYSQL_HOST>:3306/student_portfolio_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - key: DB_USERNAME
        value: <MYSQL_USERNAME>
      - key: DB_PASSWORD
        value: <MYSQL_PASSWORD>
